FPIdeasWatch/Controllers/DashboardController.cs
using BusinessLogicLayer.BLL;
using DataModel.BO;
using DataModel.Utility.Consts;
using FPIdeasWatch.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using PagedList;

namespace FPIdeasWatch.Controllers
{
    [IsSessionExpired]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            ViewBag.Active_Dashboard = "active";
            IdeasWatchList ideas = Dashboard.GetIdeasListForDashboard(IdeaStatus.Approved);
            ideas.IdeasWatchDetailList.ToPagedList(1,PagingSize.Page);
            return View(ideas);
        }
        public JsonResult GetIdeaStatusDataForChartData()
        {
            List<DataModel.BO.ChartView> result = BusinessLogicLayer.BLL.Dashboard.GetIdeaStatusForChartData();           
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetIdeaWithStatusForDashboard(int ideaStatusid)
        {
            ViewBag.Active_Dashboard = "active";
            IdeasWatchList ideas = Dashboard.GetIdeasListForDashboard(ideaStatusid);
            return PartialView("_IdeaListDashboard", ideas);
        }
        public ActionResult IdeaList(string ideaStatusId="1")
        {
            ViewBag.Active_Dashboard = "active";
            ViewBag.IdeaList = "IdeaList";
            IdeasWatchList ideas = Dashboard.GetIdeasForIdeaList(Convert.ToInt32(ideaStatusId));
            return View(ideas);
        }

        public ActionResult GetIdeaWithStatusForIdeaList(string ideaStatusId = "1")
        {
            IdeasWatchList ideas = Dashboard.GetIdeasForIdeaList(Convert.ToInt32(ideaStatusId));
            return PartialView("_IdeaListDashboard", ideas);
        }
    }
}

FPIdeasWatch/Controllers/ManageUserController.cs
using FPIdeasWatch.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogicLayer.BLL;
using DataModel.Utility;

namespace FPIdeasWatch.Controllers
{
    [IsSessionExpired]
    [IsSuperAdmin]
    public class ManageUserController : Controller
    {
        // GET: ManageUser
        public ActionResult Index()
        {
            ViewBag.Active_ManagerUser = "active";
            var userOfReviewpanel = BusinessLogicLayer.BLL.User.GetUserOfReviewPanel();
            var userWithoutReviewpanel = BusinessLogicLayer.BLL.User.GetUserWithoutReviewPanel();
            var superAdminList = DataModel.Utility.Base.SuperAdmin().OrderBy(x=>x).ToList();
            var tuple = Tuple.Create<List<DataModel.BO.UserDetail>, List<DataModel.BO.UserDetail>, List<string>>(userOfReviewpanel, userWithoutReviewpanel, superAdminList);
            return View(tuple);
        }

        public JsonResult AddingMembersInReviewPanel(int[] userId)
        {
            var result = BusinessLogicLayer.BLL.User.AssignRole(userId,DataModel.Utility.Consts.Role.ReviewPanelId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult RemoveMemberFromReviewPanel(int userId)
        {
            var result = BusinessLogicLayer.BLL.User.RemoveRole(userId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

FPIdeasWatch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link id="siteicon" rel="shortcut icon" type="images/favicon" href="~/Content/images/favicon.ico">
    <title>@ViewBag.Title - Idea Next</title>
    @Styles.Render("~/Content/css")
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    @*@Scripts.Render("~/bundles/modernizr")*@
    @*@Scripts.Render("~/bundles/HighCharts")*@

    <script src="~/Scripts/HighChart/highcharts.js"></script>
    @*<script src="http://code.highcharts.com/highcharts.js"></script>*@


</head>
<body>

    <header class="navbar-fixed-top">
        <div class="header__inner container">
            <a href="@Url.Action("Index","Dashboard")"  class="header__logo" target="_blank">
                <img src="~/Content/images/logo.png" alt="" />
            </a>
            <span class="header__info"><strong>Idea Next</strong> - Share Your Ideas</span>

            @Html.Partial("_LoginPartial")
        </div>
    </header>

    @*---------Loader----------*@
    <div id="app-loader-overlay" class="app-loader-overlay"></div>
    <div id="loading" class="app-loader"></div>
    @*---------Loader----------*@


    <main class="container body-content">
    
            @Html.Partial("_LeftMenu")
 
        @RenderBody()

        <footer>
            <p>&copy; @DateTime.Now.Year - Fareportal. All rights are reserved.</p>
        </footer>
    </main>
    @*<div style="display:none;">
            <div id="wrapper"></div>
            <input id="add" type="button" value="Add text field" />
            <textarea id="dummy" name="dummy" cols="40" class="dummy"></textarea>
        </div>*@





    <div class="alertHolder">
        <div class="alert alert-info alert-block" id="mainWarningMsg" style="display: none;">
            <a herf="javascript:void(0)" class="closeBtn">x</a>
            <div id="mainWarningMsg1"></div>

        </div>
        <div class="alert alert-success" id="mainSuccessMsg" style="display: none;">
            <a herf="javascript:void(0)" class="closeBtn">×</a>
            <div id="mainSuccessMsg1"></div>
        </div>
        <div class="alert alert-danger" id="mainErrorMsg" style="display: none;">
            <a herf="javascript:void(0)" class="closeBtn">×</a>
            <div id="mainErrorMsg1"></div>
        </div>
    </div>
    @Scripts.Render("~/bundles/scripts")
    
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script src="~/Scripts/nicEdit-latest.js"></script>
       <script src="~/Scripts/IdeaWatch.js"></script>
        <link href="~/Content/jquery.tagsinput.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.tagsinput.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>

    @Scripts.Render("~/bundles/multiSelect")
    @Scripts.Render("~/bundles/ManageUser")

    @RenderSection("scripts", required: false)
    <script>

        $(function () {
            $('.alert .closeBtn').click(function () {
                $(this).parent().hide();
            });

        });

    </script>




</body>
</html>

FPIdeasWatch/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link id="siteicon" rel="shortcut icon" type="images/favicon" href="~/Content/images/favicon.ico">
    <title>_Layout2</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

FPIdeasWatch/Views/Shared/_Layout3.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link id="siteicon" rel="shortcut icon" type="images/favicon" href="~/Content/images/favicon.ico">
    <title>_Layout3</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

FPIdeasWatch/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link id="siteicon" rel="shortcut icon" type="images/favicon" href="~/Content/images/favicon.ico">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <script src="~/Scripts/jquery-1.10.2.js"></script>
</head>
<body>
    <div>
        <header class="navbar-fixed-top">
            <div class="header__inner container">
                <a href="@Url.Action("Index","Dashboard")" class="header__logo" target="_blank">
                    <img src="~/Content/images/logo.png" alt="" />
                </a>
                <span class="header__info"><strong>Idea Next</strong> - Share Your Ideas</span>
                @Html.Partial("_LoginPartial")
            </div>
        </header>
        <div class="container body-content">
            @RenderBody()
        </div>
        </div>
    <div id="loading" class="app-loader"></div>
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $('div.profileDesc').hide();
            $(document).on('click', '#btnLoginSubmit', function () {   
                $('#loading, #app-loader-overlay').show();
            });
        });
    </script>
</body>
</html>

FPIdeasWatch/Views/Shared/_LeftMenu.cshtml
 
            <ul class="nav nav-tabs">
                <li role="presentation" class="@ViewBag.Active_Dashboard  is--Dashboard">@Html.ActionLink("Dashboard", "Index", "Dashboard")<i class="icon icon-dashboard"></i></li>
                <li role="presentation" id="viewIdeali" class="@ViewBag.Active_ViewIdea is--AddIdea">@Html.ActionLink("View Idea", "ViewIdeasWatch", "IdeaWatch")<i class="icon icon-lightbulb"></i></li>
                <li role="presentation" class="@ViewBag.Active_AddIdea is--AddIdea">@Html.ActionLink("Add Idea", "Index", "IdeaWatch")<i class="icon icon-lightbulb"></i></li>
                @if (DataModel.Utility.CurrentUser.CurrentUserDetail.IsSuperAdmin || DataModel.Utility.CurrentUser.CurrentUserDetail.IsReviewPanelMember)
                {
                    <li role="presentation" class="@ViewBag.Active_PendingIdea is--AddIdea">@Html.ActionLink("Manage Idea", "PendingReview", "IdeaWatch")<i class="icon icon-lightbulb"></i></li>

                }
                @if (DataModel.Utility.CurrentUser.CurrentUserDetail.IsSuperAdmin)
                {
                    <li role="presentation" class="@ViewBag.Active_ManagerUser is--ManageUser">@Html.ActionLink("Manage User", "Index", "ManageUser")<i class="icon icon-user2"></i></li>
                }
                
            </ul>
       